version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    volumes:
      - "database:/var/lib/mysql/Z"
    networks:
      - MojaveNet

  nginx:
    container_name: nginx
    image: nginx
    volumes:
    - "webfiles:/etc/nginx/templates/Z"
    ports:
    - "443:42/tcp"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=42
    networks:
      - MojaveNet

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - MojaveNet

networks:
  MojaveNet:
    name: MojaveNet
    driver: bridge


volumes:
  database:
    name: database
    driver_opts:
      type: volume
      device: /home/xmatute-/data/database # tienen que existir
      o: bind
  webfiles:
    name: webfiles
    driver_opts:
      type: volume
      device: /home/xmatute-/data/webfiles # tienen que existir
      o: bind

