version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    image: mariadb
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - MojaveNet
    restart: always
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./srcs/nginx
    image: nginx
    volumes:
    - "webfiles:/etc/nginx/templates"
    ports:
    - "443:443/tcp"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=443
    networks:
      - MojaveNet
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress
    image: wordpress
    networks:
      - MojaveNet
    restart: always
    volumes:
      - "webfiles:/var/www/html"
    env_file:
      - .env
    depends_on:
      - mariadb
    

networks:
  MojaveNet:
    name: MojaveNet
    driver: bridge


volumes:
  database:
    name: database
    driver_opts:
      type: volume
      device: /home/xmatute-/data/database # tienen que existir
      o: bind
  webfiles:
    name: webfiles
    driver_opts:
      type: volume
      device: /home/xmatute-/data/webfiles # tienen que existir
      o: bind

