# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: xmatute- <xmatute-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/26 19:49:51 by xmatute-          #+#    #+#              #
#    Updated: 2023/12/26 19:51:06 by xmatute-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:oldstable

# Etiqueta del mantenedor
LABEL maintainer="xmatute- <xmatute-@student.42.fr>"

# Comando por defecto para mostrar la versión de Linux al iniciar el contenedor
CMD ["bash", "-c", "echo 'Nginx container' && echo -n 'OS: ' && uname -r"]
